#!/bin/bash
tar -xvf FW.tar.gz
python3 Unlock_Flash.py
python3 Firmware_Upgrade.py
python3 Lock_Flash.py
rm efirmware
rm FW.tar.gz
rm Lock_Flash.py
rm Firmware_Upgrade.py
rm Unlock_Flash.py
rm STM32_Bootloader_Host.py
